<?php include('layout/header.phtml'); ?>
<div class="grid-container">
    <div class="grid-x grid-margin-x">
        <div class="medium-6 cell">
        <h3>
            <?php if ($editedCategory ?? false):?>
                Edit category
            <?php else: ?>
                Add a new category
            <?php endif; ?>
        </h3>
        <?php if (isset($categorySaved) && $categorySaved == true): ?>
        <div class="callout success">
            Category was saved
        </div>
        <?php elseif (isset($categorySaved) && $categorySaved == false): ?>
        <div class="callout alert">
            Fill correctly the form
        </div>
        <?php endif; ?>
        <?php if ($_SESSION['category_deleted'] ?? false): ?>
        <div class="callout alert">
            Category was deleted
        </div>
        <?php unset($_SESSION['category_deleted']); endif; ?>
            <form action="<?= $baseUrl; ?>save-category" method="POST">
                <label
                    >Name
                    <input type="text" name="category-name" placeholder="Name" value="<?= $editedCategory['name'] ?? null; ?>"/>
                </label>
                <label
                    >Description
                    <textarea name="category-description" placeholder="Description"><?= $editedCategory['description'] ?? null; ?></textarea>
                </label>
                <label
                    >Parent category
                    <select id="select_category_list" name="category-parent">
                        <option value="">--choose--</option>
                        <?php foreach($select_list_categories as $category_for_select ): ?>
                            <?php if(isset($editedCategory) && $editedCategory->parent_id == $category_for_select['id']): ?>
                            <option value="<?= $category_for_select['id']; ?>" selected><?= $category_for_select['name']; ?></option>
                            <?php else: ?>
                            <option value="<?= $category_for_select['id']; ?>"><?= $category_for_select['name']; ?></option>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </select>
                </label>
                <input
                    type="submit"
                    class="button expanded"
                    value="Save category"
                />
                <?php if(isset($editedCategory)): ?>
                <input type="hidden" name="category_id" value="<?= $editedCategory->id; ?>"/>
                <?php endif; ?>
            </form>
        </div>

        <div class="medium-6 large-5 cell large-offset-1">
        <div class="basic-card">
            <div class="basic-card-content content callout secondary">
            <h5><?= $category->name ?? 'Choose a category from the menu'; ?></h5>
            <?php if ($category->description ?? false): ?>
            <p>
                <?= $category->description; ?>
            </p>
            </div>
            <div class="links callout primary">
                <ul class="menu">
                    <li>
                        <a href="<?= $baseUrl; ?>edit-category/<?= $category->id; ?>">Edit</a>
                    </li>
                    <li>
                        <a id="delete-category-confirmation" onclick="return confirm('Are you sure?')" href="<?= $baseUrl; ?>delete-category/<?= $category->id; ?>">Delete</a>
                    </li>
                </ul>
            <?php endif; ?>
            </div>
        </div>
        </div>
    </div>

    <hr />
</div>
<?php include('layout/footer.phtml'); ?>

